# Generated by Django 5.0.4 on 2024-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='save_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
