# Generated by Django 5.0.4 on 2024-05-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_save_count_chat_slug'),
    ]

    operations = [
    ]



