# Generated by Django 5.0.4 on 2024-05-31 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20240531_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
