# Generated by Django 5.0.4 on 2024-06-01 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_chat_last_accessed_chat_unique_id_alter_chat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
