# Generated by Django 5.0.4 on 2024-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chat_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unique_id',
        ),
    ]
