# Generated by Django 5.0.4 on 2024-06-01 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_remove_chat_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
